### ISSUE TITLE
[Feature request] make map window resizeable

### ISSUE THREAD

**Issue by shenjackyuanjie** [lovexyn0827/Chunkmap#1]
Can the map window resizeable?
And maybe also and a few button on it to make it more easy to use?
and could it be saved into config file?

**Comment by lovexyn0827** [comment]
Sorry for replying so late.
Now the window has been made resizeable, a menu has been added, and moving the map by dragging has been supported.
But a config file is not very useful as there are few things to configurate before using the map. Maybe it will be introduced this summer when more features like async renderers are added.

**Comment by lovexyn0827** [comment]
But currently only MC1.16 is supported, versions compatble with MC1.17 or beyond will be there when the network environment gets better.

**Comment by shenjackyuanjie** [comment]
\o/
thanks!
it's fine, (afterall, my main version is 1165)

**Comment by shenjackyuanjie** [comment]
BTW, would you like to add support version on modfile's name?
